#!/usr/bin/env python3
"""
Generate embedded assets for the ESP32 weather display:
  - Proportional bitmap fonts (DejaVu Sans Bold) rendered via PIL
  - Weather icons drawn programmatically (two color planes), downsampled

Outputs C header files into main/generated/.
"""
import os
import sys
from PIL import Image, ImageDraw, ImageFont

FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "main", "generated")

SMALL_CAP_TARGET = 11   # px cap height for small text
BIG_CAP_TARGET = 34     # px cap height for big temperature digits

SUPERSAMPLE = 8


def find_font_size(cap_target, sample="H"):
    """Return truetype pixel size whose cap height is ~ cap_target."""
    lo, hi = 4, 200
    size = 12
    for _ in range(40):
        size = (lo + hi) // 2
        f = ImageFont.truetype(FONT_PATH, size)
        bbox = f.getbbox(sample)
        cap = bbox[3] - bbox[1]
        if cap < cap_target:
            lo = size + 1
        else:
            hi = size - 1
        if abs(cap - cap_target) <= 1:
            break
    return size


def render_glyphs(size):
    """Render all needed codepoints, return dict cp -> glyph dict."""
    font = ImageFont.truetype(FONT_PATH, size)
    ascent, descent = font.getmetrics()
    canvas_h = ascent + descent

    glyphs = {}
    cps = list(range(32, 127)) + [0x00B0]  # printable ASCII + degree sign
    for cp in cps:
        ch = chr(cp)
        bbox = font.getbbox(ch)
        x0, y0, x1, y1 = bbox
        w = max(x1 - x0, 1)
        advance = int(font.getlength(ch)) + 1
        img = Image.new("L", (w, canvas_h), 0)
        d = ImageDraw.Draw(img)
        d.text((-x0, 0), ch, font=font, fill=255)

        # pack 1bpp, LSB first, row-aligned to bytes
        rowbytes = (w + 7) // 8
        data = bytearray(rowbytes * canvas_h)
        px = img.load()
        for yy in range(canvas_h):
            for xx in range(w):
                if px[xx, yy] > 127:
                    data[yy * rowbytes + (xx >> 3)] |= 1 << (xx & 7)
        glyphs[cp] = {
            "cp": cp, "w": w, "h": canvas_h,
            "advance": advance, "rowbytes": rowbytes, "data": bytes(data),
        }
    return glyphs


def emit_font_header(path, name, glyphs, guard):
    lines = [
        "/* generated by tools/gen_assets.py -- do not edit */",
        "#ifndef %s" % guard,
        "#define %s" % guard,
        "#include <stdint.h>",
        "#include \"font_types.h\"",
        "",
    ]
    # data blobs
    lines.append(f"static const uint8_t {name}_blob[] = {{")
    for cp in sorted(glyphs):
        g = glyphs[cp]
        lines.append("    /* U+%04X '%s' */" % (cp, chr(cp) if cp < 127 else "deg"))
        row = []
        for i, b in enumerate(g["data"]):
            row.append("0x%02X" % b)
            if len(row) == 12:
                lines.append("    " + ", ".join(row) + ",")
                row = []
        if row:
            lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    lines.append("")
    lines.append(f"static const glyph_t {name}[] = {{")
    off = 0
    for cp in sorted(glyphs):
        g = glyphs[cp]
        lines.append(
            "    {0x%04X, %d, %d, %d, %d, &%s_blob[%d]}," % (
                cp, g["w"], g["h"], g["advance"], g["rowbytes"], name, off))
        off += len(g["data"])
    lines.append("};")
    lines.append(f"#define {name.upper()}_COUNT {len(glyphs)}")
    lines.append("")
    lines.append("#endif")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", path, f"({len(glyphs)} glyphs, {off} bytes of data)")


# ---------------------------------------------------------------- icons ---

S = 32  # icon grid size
SC = S * SUPERSAMPLE
ICON_SIZE = S
ICON_ROWS = (S + 7) // 8


def canvas():
    img = Image.new("L", (SC, SC), 0)
    d = ImageDraw.Draw(img)
    return img, d


def downscale(img):
    img = img.resize((S, S), Image.BOX)
    out = bytearray(S * ((S + 7) // 8))
    px = img.load()
    for yy in range(S):
        for xx in range(S):
            if px[xx, yy] > 30:
                out[yy * ((S + 7) // 8) + (xx >> 3)] |= 1 << (xx & 7)
    return bytes(out)


def ellipse(d, cx, cy, rx, ry, fill=255):
    x0 = (cx - rx) * SUPERSAMPLE
    y0 = (cy - ry) * SUPERSAMPLE
    x1 = (cx + rx) * SUPERSAMPLE
    y1 = (cy + ry) * SUPERSAMPLE
    d.ellipse([x0, y0, x1, y1], fill=fill)


def rect(d, x0, y0, x1, y1, fill=255):
    d.rectangle([x0 * SUPERSAMPLE, y0 * SUPERSAMPLE,
                 x1 * SUPERSAMPLE, y1 * SUPERSAMPLE], fill=fill)


def line(d, p0, p1, w=2, fill=255):
    d.line([p0[0] * SUPERSAMPLE, p0[1] * SUPERSAMPLE,
            p1[0] * SUPERSAMPLE, p1[1] * SUPERSAMPLE],
           fill=fill, width=int(w * SUPERSAMPLE))


def draw_cloud(d, cx=16, cy=18, r=8, fill=255):
    """cloud made of overlapping circles + base rect"""
    ellipse(d, cx, cy, r * 0.95, r * 0.72, fill)
    ellipse(d, cx - r * 0.8, cy + r * 0.25, r * 0.62, r * 0.5, fill)
    ellipse(d, cx + r * 0.8, cy + r * 0.25, r * 0.62, r * 0.5, fill)
    ellipse(d, cx - r * 0.35, cy - r * 0.55, r * 0.52, r * 0.5, fill)
    rect(d, cx - r * 0.9, cy + r * 0.15, cx + r * 0.9, cy + r * 0.75, fill)


def draw_sun(d, cx=16, cy=16, r=6, rays=True, fill=255):
    ellipse(d, cx, cy, r, r, fill)
    if rays:
        for k in range(8):
            a = k * 45
            import math
            a = math.radians(a)
            p0 = (cx + (r + 1.5) * math.cos(a), cy + (r + 1.5) * math.sin(a))
            p1 = (cx + (r + 4.5) * math.cos(a), cy + (r + 4.5) * math.sin(a))
            line(d, p0, p1, w=1.6, fill=fill)


def icon_sun():
    m, d = canvas()
    draw_sun(d)
    return downscale(m), bytes(len(downscale(m)))


def icon_partly():
    m, d = canvas()
    detail, dd = canvas()
    draw_sun(dd, cx=11, cy=11, r=4, rays=True)
    draw_cloud(d, cx=19, cy=18, r=8)
    return downscale(m), downscale(detail)


def icon_cloud():
    m, d = canvas()
    draw_cloud(d)
    return downscale(m), bytes(len(downscale(m)))


def icon_rain():
    m, d = canvas()
    detail, dd = canvas()
    draw_cloud(d)
    for x in (10, 14, 18, 22):
        line(dd, (x, 27), (x + 2, 31), w=1.4)
    return downscale(m), downscale(detail)


def icon_snow():
    m, d = canvas()
    detail, dd = canvas()
    draw_cloud(d)
    for x, y in ((11, 27), (17, 29), (23, 27)):
        line(dd, (x - 2, y), (x + 2, y), w=1.3)
        line(dd, (x, y - 2), (x, y + 2), w=1.3)
        line(dd, (x - 1.4, y - 1.4), (x + 1.4, y + 1.4), w=1.3)
        line(dd, (x - 1.4, y + 1.4), (x + 1.4, y - 1.4), w=1.3)
    return downscale(m), downscale(detail)


def icon_thunder():
    m, d = canvas()
    detail, dd = canvas()
    draw_cloud(d)
    bolt = [(18, 24), (12, 30), (15, 30), (12, 34), (20, 27), (17, 27)]
    dd.polygon([(x * SUPERSAMPLE, y * SUPERSAMPLE) for x, y in bolt], fill=255)
    return downscale(m), downscale(detail)


def icon_fog():
    m, d = canvas()
    detail, dd = canvas()
    draw_sun(dd, cx=9, cy=9, r=3.2, rays=True)
    for y in (16, 21, 26):
        rect(d, 5, y - 1, 27, y + 1)
    return downscale(m), downscale(detail)


ICONS = {
    "sun": icon_sun,
    "partly": icon_partly,
    "cloud": icon_cloud,
    "rain": icon_rain,
    "snow": icon_snow,
    "thunder": icon_thunder,
    "fog": icon_fog,
}


def emit_icons(path):
    rows = ICON_ROWS  # 4
    lines = [
        "/* generated by tools/gen_assets.py -- do not edit */",
        "#ifndef _GEN_ICONS_H_",
        "#define _GEN_ICONS_H_",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        "#define ICON_SIZE 32",
        "#define ICON_ROWS 4",
        "",
        "typedef struct {",
        "    const uint8_t *main;",
        "    const uint8_t *detail;",
        "} weather_icon_t;",
        "",
    ]
    for name, fn in ICONS.items():
        main_bits, detail_bits = fn()
        # render a preview PNG for visual check
        preview = Image.new("RGB", (S * 8, S * 8), (20, 24, 34))
        pp = preview.load()
        for yy in range(S):
            for xx in range(S):
                mi = main_bits[yy * ICON_ROWS + (xx >> 3)] & (1 << (xx & 7))
                de = detail_bits[yy * ICON_ROWS + (xx >> 3)] & (1 << (xx & 7))
                color = (210, 220, 235) if de else (240, 200, 60)
                if mi:
                    color = (176, 190, 197)
                for sy in range(8):
                    for sx in range(8):
                        pp[xx * 8 + sx, yy * 8 + sy] = color
        preview.save(os.path.join("/tmp", f"icon_{name}.png"))
        lines.append(f"static const uint8_t icon_{name}_main[{ICON_SIZE * ICON_ROWS}] = {{")
        for i in range(0, len(main_bits), 16):
            lines.append("    " + ", ".join("0x%02X" % b for b in main_bits[i:i + 16]) + ",")
        lines.append("};")
        if any(detail_bits):
            lines.append(f"static const uint8_t icon_{name}_detail[{ICON_SIZE * ICON_ROWS}] = {{")
            for i in range(0, len(detail_bits), 16):
                lines.append("    " + ", ".join("0x%02X" % b for b in detail_bits[i:i + 16]) + ",")
            lines.append("};")
            lines.append(f"static const weather_icon_t icon_{name} = {{icon_{name}_main, icon_{name}_detail}};")
        else:
            lines.append(f"static const weather_icon_t icon_{name} = {{icon_{name}_main, NULL}};")
        lines.append("")
        # ascii preview
        print(f"--- icon {name} ---")
        for yy in range(S):
            row = ""
            for xx in range(S):
                mi = main_bits[yy * ICON_ROWS + (xx >> 3)] & (1 << (xx & 7))
                de = detail_bits[yy * ICON_ROWS + (xx >> 3)] & (1 << (xx & 7))
                if mi:
                    row += "#"
                elif de:
                    row += "o"
                else:
                    row += "."
            print(row)
    lines.append("#endif")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", path)


def emit_sky(path):
    img_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "images", "sky.png")
    img = Image.open(img_path).convert("RGB").resize((172, 320))
    px = img.load()
    out = []
    for y in range(320):
        for x in range(172):
            r, g, b = px[x, y]
            v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | ((b & 0xF8) >> 3)
            out.append(v)
    lines = [
        "/* generated by tools/gen_assets.py -- do not edit */",
        "#ifndef _GEN_SKY_H_",
        "#define _GEN_SKY_H_",
        "#include <stdint.h>",
        "",
        "#define SKY_W 172",
        "#define SKY_H 320",
        "",
        "static const uint16_t sky_bg[SKY_W * SKY_H] = {",
    ]
    for i in range(0, len(out), 16):
        lines.append("    " + ", ".join("0x%04X" % v for v in out[i:i + 16]) + ",")
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", path, f"({len(out)} pixels)")


def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    small_size = find_font_size(SMALL_CAP_TARGET)
    big_size = find_font_size(BIG_CAP_TARGET)
    print(f"small font size={small_size}px, big font size={big_size}px")

    emit_font_header(os.path.join(OUT_DIR, "font_small.h"), "font_small",
                     render_glyphs(small_size), "GEN_FONT_SMALL_H")
    emit_font_header(os.path.join(OUT_DIR, "font_big.h"), "font_big",
                     render_glyphs(big_size), "GEN_FONT_BIG_H")
    emit_icons(os.path.join(OUT_DIR, "icons.h"))
    emit_sky(os.path.join(OUT_DIR, "sky.h"))


if __name__ == "__main__":
    sys.exit(main())